### ISSUE TITLE
BattleSort Doesn't Recognize Some Returns

### ISSUE THREAD

**Issue by metricSparrow** [anonmos/battlesort#12]
When Dan was sorting a list, he pasted in items and our system didn't recognize the returns and break them into items to be sorted (it all became one big item). 

So he added commas and was off to the races, but we should see if there are multiple forms of line breaks we need to be looking for.

**Comment by metricSparrow** [comment]
Note: I have not been able to reproduce this yet.

**Comment by anonmos** [comment]
@metricSparrow if Dan can reproduce that'd be extremely helpful.  I'd be curious to see how he did it.

**Comment by metricSparrow** [comment]
Tried to get him to, no dice. Let's table it till it comes up again.

**Comment by anonmos** [comment]
@metricSparrow sounds good, closing for now then we can reopen later if it pops back up.
