### ISSUE TITLE
Comma use in newline-separated lists breaks items into multiple parts

### ISSUE THREAD

**Issue by metricSparrow** [anonmos/battlesort#13]
This has happened to a couple testers now, they'll enter a list like:

1. Make breakfast
2. Find the camping cot, clean it, and take a nap
3. Do some backflips

Line 2. will get broken into 3 items when really it should be one

**Comment by metricSparrow** [comment]
Potential solution, let the user select their delimiter. (If we go this path, default the format we return the sorted list in to be the same).

**Comment by anonmos** [comment]
@metricSparrow another solution - right now it parses commas first, checks to see if the array is length of 1, and if so swaps to parsing newlines.  If I parse newlines first under that same logic it'd fix the problem.

I'm doubting that there is a "mixed mode" version of this for users.  But there is a newline-or-not approach that keeps everything whole.  I like the idea of keeping the interface as simplistic and clean as possible for the user.

**Comment by anonmos** [comment]
Implemented suggested solution with https://github.com/anonmos/battlesort/commit/4e30c20680a3a30c21350571925eb000936aced9

**Comment by metricSparrow** [comment]
You are brilliant.
