### ISSUE TITLE
A Duplicate Comparison snuck through

### ISSUE THREAD

**Issue by metricSparrow** [anonmos/battlesort#14]
![Screen Shot 2020-07-15 at 12 27 56 PM](https://user-images.githubusercontent.com/8452408/87587732-55332d00-c697-11ea-861c-039825c116ac.png)

* Comparison right before this one was a `it's equal`
* List used was as follows:
```Reports for HCA (90m)
OLV for CT Scanner (3h)
Finish Last Design Reviews (3h)
Last Mini Specs (90m)
Thorough Review of Intern Projects (90m)
How much time left in Internship? Set Goals (30m)
Create New Categories (16hr
Update Oseola OLVs for Lisa -30% (90m)
Parse/Filter Big Buyer List (8h)
Perfect Audience Category Retargeting v1 (8h)
Facebook Category Retargeting v1 (8h)
Respond to Addressable w/ new plan (20m)
Chat with Mitch about New Addressable Plan (30m)
Email Catch up (60m)
Get Tim to help Interns with DotMed Scrape (5m)
Pass Interns real examples to work with [end to end] (30m)
```

**Comment by metricSparrow** [comment]
Reproduced:
1. Use this starting set:
```Item 1
Item 2
Duplicate
Item 4
Item 5```
2. Click `left`, `left`, `equal`, `equal`
3. See duplicate result

**Comment by anonmos** [comment]
@metricSparrow good catch.  I'm going to consolidate the duplicate-finder code into the auto-sort code and run it all from the same place.  That should fix it and make the code cleaner.

**Comment by anonmos** [comment]
Fixed by https://github.com/anonmos/battlesort/commit/edddaa29a00bb614b2394a0eabe6086e9deacc83

Couldn't replicate given the sample case after fix.  Closing as complete.  If it pops up again let me know.
