### ISSUE TITLE
Highlight the comparison text

### ISSUE THREAD

**Issue by anonmos** [anonmos/battlesort#8]
The word "greater" on the "Which of these items is greater?" text right now is only bolded, and it doesn't quite stand out enough.  Jesse highlighted the background in yellow and it actually looked pretty cool.  Let's do that.

**Comment by metricSparrow** [comment]
Obnoxious yellow. It hurts the eyes, but it'll also keep them on what's important. 
![Screen Shot 2020-07-14 at 12 40 52 PM](https://user-images.githubusercontent.com/8452408/87469709-8ac11300-c5d0-11ea-9713-1df5b9357da0.png)

**Comment by anonmos** [comment]
Implemented in https://github.com/anonmos/battlesort/commit/72158eaa48858542c6554a993d52ea6160676faf
