### ISSUE TITLE
New List of Comparable Things

### ISSUE THREAD

**Issue by anonmos** [anonmos/battlesort#9]
Right now, we have a test list of numbers that allows you to sort things.  That doesn't really communicate what this thing does.  Let's change it to simple household stuff (do dishes, rake leaves, vacuum, pet cat, etc.) so that a user can clearly see how this whole things works.

**Comment by metricSparrow** [comment]
I love how idyllic this list is so far.
`bake a pie, read a book` etc

**Comment by anonmos** [comment]
Updated in https://github.com/anonmos/battlesort/commit/9a8eaaa4b64694752d0f169e94bbd688878042d6
